version: '2'
services:
  postgres:
    image: postgres:9.6
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_DB=springbatch
    - POSTGRES_USER=marcosbarra
    - POSTGRES_PASSWORD=12345
    - MAX_CONNECTIONS=300